config/routes.rb
Equiv::Application.routes.draw do

  get 'interests/new' => 'interests#new'
  post 'interests' => 'interests#create'
  match 'interests/thanks' => 'interests#thanks'

  root :to => 'interests#new'

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :requirements
	has_many :curriculums, :through => :requirements
end

app/models/curriculum.rb
class Curriculum < ActiveRecord::Base
	belongs_to :degree
	has_many :requirements
	has_many :courses, :through => :requirements

end

app/models/degree.rb
class Degree < ActiveRecord::Base
	belongs_to :school
	has_many :curriculums
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	validates :name, :email, :degree, :presence=>true
	validates :email, :uniqueness=>true
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
	belongs_to :curriculum
	belongs_to :course
end

app/models/school.rb
class School < ActiveRecord::Base
	has_many :degrees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  # GET /interests/new
  # GET /interests/new.json
  def new
    @interest = Interest.new
    @degrees = Degree.find(:all, :order=>'name')


    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @interest }
    end
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(params[:interest])
    @degrees = Degree.find(:all, :order=>'name')

    respond_to do |format|
      if @interest.save
        format.html { redirect_to :action => "thanks", :notice => 'Interest was successfully created.' }
        format.json { render :json => @interest, :status => :created, :location => @interest }
      else
        format.html { render :action => "new" }
        format.json { render :json => @interest.errors, :status => :unprocessable_entity }
      end
    end
  end

  # GET /interests/thanks
  def thanks
    @thanks = true
    respond_to do |format|
      format.html { render :action => "new" }
      format.json { render :json => @interest.errors, :status => :unprocessable_entity }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def facebook_like
		content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=#{CGI::escape(request.url)}&layout=standard&show_faces=true&width=450&action=like&font=arial&colorscheme=light&height=80", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like
	end
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_form.html.erb
<%= simple_form_for(@interest, :html => {:class => 'form-vertical well' }) do |f| %>
  <% if f.error_notification %>
    <div class="alert alert-error fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= f.error_notification %>
      <ul>
      <% @interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :name, :input_html => { :class => "span5" }, :placeholder => "So we don't have to refer to you as \"hey you\"..." %>
    <%= f.input :email, :input_html => { :class => "span5" }, :placeholder => "We want to let you know when its ready..." %>
    <%= f.input :degree, :collection => @degrees, :input_html => { :class => "span5" } %>
    <%= f.input :notes, :input_html => {:class => "span5", :rows=>'5'}, :placeholder => "Tell us all about you..." %>

    <%= f.submit :class => "btn btn-warning" %>


<% end %>

app/views/interests/edit.html.erb
<h1>Editing interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<h1>Listing interests</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Degree</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interests.each do |interest| %>
  <tr>
    <td><%= interest.name %></td>
    <td><%= interest.email %></td>
    <td><%= interest.degree %></td>
    <td><%= link_to 'Show', interest %></td>
    <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
    <td><%= link_to 'Destroy', interest, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<div class="container">
	<div class="row" style="margin-bottom: 36px;">
		<div class="span6 offset2">
			<h1 style="font-size: 72px; letter-spacing: -1px; line-height: 1; text-rendering: optimizelegibiliy;" class="tk-museo">equiv.org</h1>
			<p class="lead">Congratulations, you have found a brand-new web application with a very big idea.  <strong>If you like what we are doing, here is how you could help.</strong></p>
		</div>
	</div>

	<div class="row">
		<div class="span6 offset2">
			<h2 class="tk-museo">1. Tell us you are interested!</h2>
			<small>The more we know people are interested, the faster we work</small> 
			<% if @thanks %>
				<div class="alert alert-success">Thanks for the feedback!  We will let you know when things are ready!</div>
			<% else %>
				<%= render 'form' %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="span6 offset2">
			<h2 class="tk-museo">2. Talk it up!</h2>
			<p>Let other people know about our goal through your social network.</p>
			<p>
				<%= 	content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=#{CGI::escape('http://www.equiv.org')}&layout=standard&show_faces=true&width=450&action=like&font=arial&colorscheme=light&height=80", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like, :height=>30 %>
			</p>
		</div>
	</div>


	<div class="row">
		<div class="span6 offset2">
			<h2 class="tk-museo">2. Fork me! <small>(Are you geek enough?)</small></h2>
			<p>We are trying to help anyone receive a higher-level of education for free.  Expecting to profit off of education just doesn't seem right.  We are open sourcing the code as a result.</p>
		</div>
	</div>

</div>
<a href="http://github.com/you"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://a248.e.akamai.net/assets.github.com/img/30f550e0d38ceb6ef5b81500c64d970b7fb0f028/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6f72616e67655f6666373630302e706e67" alt="Fork me on GitHub"></a>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @interest.name %>
</p>

<p>
  <b>Email:</b>
  <%= @interest.email %>
</p>

<p>
  <b>Degree:</b>
  <%= @interest.degree %>
</p>


<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Equiv</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href="//twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
  <link href="//twitter.github.com/bootstrap/assets/css/docs.css" rel="stylesheet">
  <link href="//twitter.github.com/bootstrap/assets/js/google-code-prettify/prettify.css" rel="stylesheet">
  <script type="text/javascript" src="https://use.typekit.com/drw0kan.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>